apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: 192.168.65.3  # Yerel IP adresinizi buraya yazın
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: esprit-argo-app  # Doğru servis adı
                port:
                  number: 80  # Servis portu
