apiVersion: apps/v1
kind: Deployment
metadata:
  name: esprit-argo-app
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: esprit-argo-app
  template:
    metadata:
      labels:
        app: esprit-argo-app
    spec:
      containers:
        - name: esprit-argo-app
          image: seymurahmadov14/esprit-argo:v2  # Burayı güncelleyeceksin
          ports:
            - containerPort: 8082
