apiVersion: v1
kind: Service
metadata:
  name: esprit-argo-app
  namespace: argocd
spec:
  selector:
    app: esprit-argo-app
  ports:
    - protocol: TCP
      port: 80        # Dışarıya açılacak port
      targetPort: 8081 # Pod'un çalıştığı port
      nodePort: 31343  # Burada 31343 gibi bir port numarası verebilirsiniz
  type: NodePort
